language: node_js
node_js:
  - '8.10'
  - '10.15'
addons:
  apt:
    packages:
    - libjpeg62
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
